### PR TITLE
Add new en blog post

### PR DESCRIPTION
**Pull request by ogwata**
I translated my blog about the recent user/developer event into English. Could you proofread it for me?

### CODE REVIEW

**Comment by MurakamiShinyu** [comment]
> Part 1 Expanding World of CSS Typeetting

"Typeetting" → "Typesetting"

> 2. Development of a Japanese typesetting and processing system with powerful graphics capabilities

"Japanese typesetting and processing system" → "Japanese typesetting system"

> Saku sharply criticized…. Andreas also introduced his services, …

"also" → ""

（「サクは…を鋭く批判した。アンドレアス**も**彼のサービスを紹介した」は不自然）

> Our next event is scheduled for October. The next event is scheduled for October,

". The next event is scheduled for October" → ""

**Comment by johanneswilm-test** [comment]
It looks fine, but given that the English speakers won't be able to understand the videos in Japanese, I think it's extra important to help them with the abbreviations. Here I noticed "SNS" which I would replace with "social media" unless SNS is a specific site (that I don't know about). The other abbreviation is VFM.

**Comment by ogwata** [comment]
> > Part 1 Expanding World of CSS Typeetting
> 
> "Typeetting" → "Typesetting"
> 
> > 1. Development of a Japanese typesetting and processing system with powerful graphics capabilities
> 
> "Japanese typesetting and processing system" → "Japanese typesetting system"
> 
> > Saku sharply criticized…. Andreas also introduced his services, …
> 
> "also" → ""
> 
> （「サクは…を鋭く批判した。アンドレアス**も**彼のサービスを紹介した」は不自然）
> 
> > Our next event is scheduled for October. The next event is scheduled for October,
> 
> ". The next event is scheduled for October" → ""

修正しました！

**Comment by ogwata** [comment]
> It looks fine, but given that the English speakers won't be able to understand the videos in Japanese, I think it's extra important to help them with the abbreviations. Here I noticed "SNS" which I would replace with "social media" unless SNS is a specific site (that I don't know about). The other abbreviation is VFM.

Corrected according to the revue. Please check.

**Review by MurakamiShinyu — APPROVED** [review]

**Pull request merged**
